<!-- Footer -->
<footer id="general-footer">
  <div class="footer-row">
    <div class="footer-col">
      <a href="index.php"
        ><img
          src="images/logo-removebg-preview.png"
          class="logo"
          alt="CloudLabs logo"
      /></a>
      <p>
        Our company provides details of "Chief Technology Officer(CTO)" and
        "Cloud engineering", including base position, skills needed,
        qualification and salary average per year in Australia.
      </p>
    </div>
    <div class="footer-col">
      <h3>Contact us</h3>
      <p class="footer-email-id">
        <a href="mailto:104082552@student.swin.edu.au" class="footer-email-id"
          >Email: 104082552@student.swin.edu.au</a
        >
      </p>
      <p>Phone Number: +61423032755</p>
    </div>
    <div class="footer-col">
      <h3>Links</h3>
      <ul>
        <li><a href="./index.php">Home</a></li>
        <li><a href="./jobs.php">Jobs</a></li>
        <li><a href="./apply.php">Apply</a></li>
        <li><a href="./about.php">About</a></li>
        <li><a href="./enhancements.php">Enhancements</a></li>
        <li><a href="./phpenhancements.php">PHP Enhancements</a></li>
        <li><a href="./loginmanager.php">Manage</a></li>
      </ul>
    </div>
    <div class="footer-col">
      <h3>Sign up to our newsletter</h3>
      <form>
        <input type="email" placeholder="Enter your email here" required />
        <input type="submit" />
      </form>
    </div>
  </div>
  <hr />
  <p>CloudLabs 2023 &copy; - All Rights Reserved</p>
</footer>
